# Generated by Django 5.2.4 on 2025-07-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='item_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
