# Generated by Django 5.2.4 on 2025-07-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_question_comment_commentthumbsup'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
