# Generated by Django 5.2.4 on 2025-07-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
