# Generated by Django 5.2.4 on 2025-07-25 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
        ('item', '0001_initial'),
        ('transaction', '0002_transaction_completed_at_transaction_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='item',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='member',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='message',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='parent_offer',
        ),
        migrations.AlterField(
            model_name='offer',
            name='sender_is_agent',
            field=models.BooleanField(),
        ),
        migrations.CreateModel(
            name='NegotiationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.agent')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('agent', 'member', 'item')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_is_agent', models.BooleanField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='transaction.negotiationsession')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='transaction.negotiationsession'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
